apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: prom
data:
  prometheus.rules: |-
    groups:
    - name: example
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    rule_files: 
    - /etc/prometheus/prometheus.rules
    alerting: 
      alertmanagers:
      - static_configs:
        - targets:
          - localhost:9093
    scrape_configs: 
      - job_name: prometheus
        static_configs:
        - targets:
            - localhost:9090
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
      - job_name: example
        static_configs:
        - targets:
          - localhost:8000
      - job_name: pushgateway
        honor_labels: true
        static_configs:
        - targets:
          - localhost:9091